### ISSUE TITLE
Post-commit script

### ISSUE THREAD

**Issue by bkaluza** [sntran/trello-broker#1]
The script seems really useful. Can you provide a sample for post-commit script?

Thanks.

**Comment by sntran** [comment]
Hi there,

This was made long time ago as a broker for Bitbucket, so it should be integrated with Bitbucket and not as a standalone. In order to do that, one needs to contact Bitbucket. I could not find time to finish this project, so you are very welcome to use this as the base and complete it and submit it to Bitbucket.
